spring:
  datasource:
    hikari:
      username: root
      password: root
      jdbc-url:
      driver-class-name:
  profiles:
    active: sharding-table
  shardingsphere:
    props:
      sql-show: true

mybatis:
  mapper-locations: classpath:mapper/*.xml